[tool.poetry]
name = "wardfastapi"
version = "0.1.0"
description = ""
authors = ["ibraheem-areeda <ibraheem.areeda@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
